# Generated by Django 5.2.5 on 2025-08-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_farm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='farm',
        ),
    ]
